{
 "title": "Gatling Report",
 "description": "Gatling Report",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "granularity",
    "label": "granularity",
    "query": "1s,2s,5s,10s,30s,1m,2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": "label_values(total_started_users, simulation)"
   },
   {
    "name": "host",
    "label": "Load Station",
    "query": "label_values(requests_latency_secondsHistogram_count , instance)"
   },
   {
    "name": "request",
    "label": "Request",
    "query": "label_values(requests_latency_secondsHistogram_count, metric)"
   },
   {
    "name": "scenario",
    "label": "User (Scenario)",
    "query": "label_values(total_started_users, simulation)"
   },
   {
    "name": "duration",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Global Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indicators",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_bucket{le=\"0.8\"}[$duration])) by (job)\n/\nsum(rate(requests_latency_secondsHistogram_count[$duration])) by (job)",
     "legendFormat": "< 800 ms"
    },
    {
     "expr": "(\nsum(rate(requests_latency_secondsHistogram_bucket{le=\"1.2\"}[$duration])) by (job)\n- sum(rate(requests_latency_secondsHistogram_bucket{le=\"0.8\"}[$duration])) by (job)\n)\n/\nsum(rate(requests_latency_secondsHistogram_count[$duration])) by (job)",
     "legendFormat": "800 ms < t < 1200 ms"
    },
    {
     "expr": "(\nsum(rate(requests_latency_secondsHistogram_bucket{le=\"+Inf\"}[$duration])) by (job)\n- sum(rate(requests_latency_secondsHistogram_bucket{le=\"1.2\"}[$duration])) by (job)\n)\n/\nsum(rate(requests_latency_secondsHistogram_count[$duration])) by (job)",
     "legendFormat": "> 1200 ms"
    }
   ]
  },
  { "title": "Statistics $simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "simulation" },
  {
   "title": "Response Times",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(requests_latency_secondsHistogram_bucket{simulation=~\"$simulation\"}[$duration])) by (group, metric, sim_group_metric_hash)",
     "legendFormat": "{{group}} {{metric}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(requests_latency_secondsHistogram_bucket{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash, le))",
     "legendFormat": "99%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(requests_latency_secondsHistogram_bucket{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash, le))",
     "legendFormat": "95%ile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(requests_latency_secondsHistogram_bucket{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash, le))",
     "legendFormat": "75%ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(requests_latency_secondsHistogram_bucket{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash, le))",
     "legendFormat": "50%ile"
    },
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{oK=\"OK\",simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{oK=\"KO\",simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)",
     "legendFormat": "KO"
    },
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{oK=\"KO\",simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)\n/\nsum(rate(requests_latency_secondsHistogram_count[$duration])) by (sim_group_metric_hash)",
     "legendFormat": "KO %"
    },
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{oK=\"OK\",simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)\n/\nsum(rate(requests_latency_secondsHistogram_count{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)",
     "legendFormat": "OK %"
    },
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)\n/\nsum(rate(requests_latency_secondsHistogram_sum{simulation=~\"$simulation\"}[$duration])) by (sim_group_metric_hash)",
     "legendFormat": "Request/s"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(simulation) (total_started_users{simulation=~\"$simulation\"}) - sum by(simulation) (total_finished_users{simulation=~\"$simulation\"})",
     "legendFormat": "{{simulation}}"
    }
   ]
  },
  {
   "title": "Response/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(requests_latency_secondsHistogram_count{simulation=~\"$simulation\"}[$duration])) by (simulation)\n/\n  sum(rate(requests_latency_secondsHistogram_sum{simulation=~\"$simulation\"}[$duration])) by (simulation)",
     "legendFormat": "{{simulation}}"
    }
   ]
  }
 ]
}